
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - CI_ENVIRONMENT=development
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - ci4-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ci4_app
      POSTGRES_USER: ci4_user
      POSTGRES_PASSWORD: ci4_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci4-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - ci4-network

volumes:
  postgres_data:

networks:
  ci4-network:
    driver: bridge
